# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import message.pose_estimation_pb2 as pose__estimation__pb2


class EstimationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EstimatePoses = channel.unary_unary(
                '/godeye_service.pose_estimation.Estimation/EstimatePoses',
                request_serializer=pose__estimation__pb2.EstimateRequest.SerializeToString,
                response_deserializer=pose__estimation__pb2.EstimateResponse.FromString,
                )


class EstimationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def EstimatePoses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EstimationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EstimatePoses': grpc.unary_unary_rpc_method_handler(
                    servicer.EstimatePoses,
                    request_deserializer=pose__estimation__pb2.EstimateRequest.FromString,
                    response_serializer=pose__estimation__pb2.EstimateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'godeye_service.pose_estimation.Estimation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Estimation(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EstimatePoses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/godeye_service.pose_estimation.Estimation/EstimatePoses',
            pose__estimation__pb2.EstimateRequest.SerializeToString,
            pose__estimation__pb2.EstimateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
