agent: "TripletAgent"

train:
  device: "cuda"
  n_epochs: 100
  log_dir: "run"
  exp_name: "triplet"
  resume: false

model:
  name: "resnet18_reid"
  kwargs:
    features: 128
    classes: 1502

dataset:
  name: "market1501"
  extras: []
  root: "download"
  size: [256, 128]

dataloader:
  P: 16
  K: 4
  batch_size: 64

optimizer:
  lr: 0.001

schedular:
  step_size: 20

loss:
  margin: 0.3
