# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pose-estimation.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pose-estimation.proto',
  package='godeye_service.pose_estimation',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15pose-estimation.proto\x12\x1egodeye_service.pose_estimation\"E\n\x0f\x45stimateRequest\x12\x32\n\x03img\x18\x01 \x01(\x0b\x32%.godeye_service.pose_estimation.Image\"\xd8\x01\n\x10\x45stimateResponse\x12@\n\rposeKeypoints\x18\x01 \x03(\x0b\x32).godeye_service.pose_estimation.Keypoints\x12@\n\rfaceKeypoints\x18\x02 \x03(\x0b\x32).godeye_service.pose_estimation.Keypoints\x12@\n\rhandKeypoints\x18\x03 \x03(\x0b\x32).godeye_service.pose_estimation.Keypoints\"\x18\n\x05Image\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\"B\n\tKeypoints\x12\x35\n\x06points\x18\x01 \x03(\x0b\x32%.godeye_service.pose_estimation.Point\"+\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\x0c\n\x04\x63onf\x18\x03 \x01(\x02\x32\x82\x01\n\nEstimation\x12t\n\rEstimatePoses\x12/.godeye_service.pose_estimation.EstimateRequest\x1a\x30.godeye_service.pose_estimation.EstimateResponse\"\x00\x62\x06proto3'
)




_ESTIMATEREQUEST = _descriptor.Descriptor(
  name='EstimateRequest',
  full_name='godeye_service.pose_estimation.EstimateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='img', full_name='godeye_service.pose_estimation.EstimateRequest.img', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=126,
)


_ESTIMATERESPONSE = _descriptor.Descriptor(
  name='EstimateResponse',
  full_name='godeye_service.pose_estimation.EstimateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='poseKeypoints', full_name='godeye_service.pose_estimation.EstimateResponse.poseKeypoints', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='faceKeypoints', full_name='godeye_service.pose_estimation.EstimateResponse.faceKeypoints', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='handKeypoints', full_name='godeye_service.pose_estimation.EstimateResponse.handKeypoints', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=345,
)


_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='godeye_service.pose_estimation.Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload', full_name='godeye_service.pose_estimation.Image.payload', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=347,
  serialized_end=371,
)


_KEYPOINTS = _descriptor.Descriptor(
  name='Keypoints',
  full_name='godeye_service.pose_estimation.Keypoints',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='points', full_name='godeye_service.pose_estimation.Keypoints.points', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=373,
  serialized_end=439,
)


_POINT = _descriptor.Descriptor(
  name='Point',
  full_name='godeye_service.pose_estimation.Point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='godeye_service.pose_estimation.Point.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='godeye_service.pose_estimation.Point.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='conf', full_name='godeye_service.pose_estimation.Point.conf', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=441,
  serialized_end=484,
)

_ESTIMATEREQUEST.fields_by_name['img'].message_type = _IMAGE
_ESTIMATERESPONSE.fields_by_name['poseKeypoints'].message_type = _KEYPOINTS
_ESTIMATERESPONSE.fields_by_name['faceKeypoints'].message_type = _KEYPOINTS
_ESTIMATERESPONSE.fields_by_name['handKeypoints'].message_type = _KEYPOINTS
_KEYPOINTS.fields_by_name['points'].message_type = _POINT
DESCRIPTOR.message_types_by_name['EstimateRequest'] = _ESTIMATEREQUEST
DESCRIPTOR.message_types_by_name['EstimateResponse'] = _ESTIMATERESPONSE
DESCRIPTOR.message_types_by_name['Image'] = _IMAGE
DESCRIPTOR.message_types_by_name['Keypoints'] = _KEYPOINTS
DESCRIPTOR.message_types_by_name['Point'] = _POINT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EstimateRequest = _reflection.GeneratedProtocolMessageType('EstimateRequest', (_message.Message,), {
  'DESCRIPTOR' : _ESTIMATEREQUEST,
  '__module__' : 'pose_estimation_pb2'
  # @@protoc_insertion_point(class_scope:godeye_service.pose_estimation.EstimateRequest)
  })
_sym_db.RegisterMessage(EstimateRequest)

EstimateResponse = _reflection.GeneratedProtocolMessageType('EstimateResponse', (_message.Message,), {
  'DESCRIPTOR' : _ESTIMATERESPONSE,
  '__module__' : 'pose_estimation_pb2'
  # @@protoc_insertion_point(class_scope:godeye_service.pose_estimation.EstimateResponse)
  })
_sym_db.RegisterMessage(EstimateResponse)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), {
  'DESCRIPTOR' : _IMAGE,
  '__module__' : 'pose_estimation_pb2'
  # @@protoc_insertion_point(class_scope:godeye_service.pose_estimation.Image)
  })
_sym_db.RegisterMessage(Image)

Keypoints = _reflection.GeneratedProtocolMessageType('Keypoints', (_message.Message,), {
  'DESCRIPTOR' : _KEYPOINTS,
  '__module__' : 'pose_estimation_pb2'
  # @@protoc_insertion_point(class_scope:godeye_service.pose_estimation.Keypoints)
  })
_sym_db.RegisterMessage(Keypoints)

Point = _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), {
  'DESCRIPTOR' : _POINT,
  '__module__' : 'pose_estimation_pb2'
  # @@protoc_insertion_point(class_scope:godeye_service.pose_estimation.Point)
  })
_sym_db.RegisterMessage(Point)



_ESTIMATION = _descriptor.ServiceDescriptor(
  name='Estimation',
  full_name='godeye_service.pose_estimation.Estimation',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=487,
  serialized_end=617,
  methods=[
  _descriptor.MethodDescriptor(
    name='EstimatePoses',
    full_name='godeye_service.pose_estimation.Estimation.EstimatePoses',
    index=0,
    containing_service=None,
    input_type=_ESTIMATEREQUEST,
    output_type=_ESTIMATERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ESTIMATION)

DESCRIPTOR.services_by_name['Estimation'] = _ESTIMATION

# @@protoc_insertion_point(module_scope)
